//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace ReferenceBook.Models
{
    using System;
    using System.Collections.Generic;

    
    public partial class Person
    {
          [ScaffoldColumn(false)]
        public int Id { get; set; }

          [Required(ErrorMessage = "Name must be set")]
          [StringLength(20, MinimumLength = 3, ErrorMessage = "Name should be between 3 and 20 symbols")]
        public string FirstName { get; set; }

          [Required(ErrorMessage = "Surname must be set")]
          [StringLength(20, MinimumLength = 3, ErrorMessage = "Surname should be between 3 and 20 symbols")]
        public string LastName { get; set; }

         [Required(ErrorMessage = "Telephone must be set")]
         [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage = "Number should be like this ***-***-**** ")]
        public string Tel { get; set; }

         [DisplayFormat(ConvertEmptyStringToNull = true)]
        public string Additional_Information { get; set; }
    }
}
